### ISSUE TITLE
[Again] Uncaught TypeError: onSort is not a function

### ISSUE THREAD

**Issue by mazzalab** [react-bootstrap-table/react-bootstrap-table2#1211]
Hi all,
I know this is a duplicate of #652 but it seems that that issue was closed without providing a solution to the problem.

I am using "react-bootstrap-table-next": "^3.3.3" and my simple Component ha this constructor:

```
constructor(props) {
        var _isMounted = false;

        super(props);
        this.state = {
            data: [{ 'id': 1 }],
            columns: [{
                dataField: 'id',
                text: 'Product IDs'
            }],
            rowCount: 10
        }
    }
```
You can see that I save **data** and **columns** in the component state, which I finally update in

```
componentDidMount() {
        this._isMounted = true;

        fetch('http://127.0.0.1:5000/')
            .then(response => response.json())
            .then(data => {
                var sorted_header = this.formatHeader(data);

                if (this._isMounted) {
                    this.setState({ columns: sorted_header });
                    this.setState({ data: data });
                }
            });
    }
```

the "formatHeader" method simply formats the header of the table with things like:

```
const sorted_header = [{
            dataField: 'id',
            text: 'Product ID',
            sort: true
        }, {
            dataField: 'user',
            text: 'User',
            filter: textFilter(),
            style: {
                fontStyle: 'italic',
            },
            sort: true
        }
       ...
```
whenever I click on the header up/down arrow to sort one of these columns I get the wrror in object that points to the internal file "header-cell.js:123"
(this error in attachment)

What to do?
thanks

![Annotation 2019-12-26 211120](https://user-images.githubusercontent.com/10012441/71489150-767c1b00-2824-11ea-85f2-ce2468930a6d.png)

**Comment by amitsetty** [comment]
I was able to fix this issue by passing my data into columns by doing column = [...data]

**Comment by AllenFang** [comment]
@mazzalab upgrade to newest `react-bootstrap-table-next`, it is fixed!

**Comment by ux-powered** [comment]
Hi, I upgraded the package version (3.3.4), but the error is still here 🤔. Any workarounds?

![image](https://user-images.githubusercontent.com/39078782/74219011-41a22580-4cf7-11ea-809f-c6557ae4c0b9.png)
![image](https://user-images.githubusercontent.com/39078782/74219028-52eb3200-4cf7-11ea-9462-0bd89640f431.png)

**Comment by mazzalab** [comment]
yes indeed, it is not fixed.
It seems that BootstrapTable does not work well with state variables. If possible, try passing props and not state variables to the table. 

```
<BootstrapTable
                    keyField="id"
                    data={this.props.data}
```
it should work.

read also: https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/652#issuecomment-566781605

**Comment by ux-powered** [comment]
Thank you for the info, I will try it 🙂

**Comment by ricardobarbosahe** [comment]
@mazzalab None of the alternatives worked :/ I'm passing the columns through props (tried hardcoded as well), latest versions (react: ^16.12.0, react-bootstrap-table-next: ^3.3.4, react-bootstrap-table2-paginator: ^2.1.0, react-bootstrap-table2-toolkit: ^2.1.2)

The default sort arrow is not in the "active" state at the start, and when I go to another page (using pagination), this arrow appears active and the sort works, but only on even pages! :S

**Comment by Grafomap** [comment]
> @mazzalab upgrade to newest `react-bootstrap-table-next`, it is fixed!

It is not fixed on 3.3.4

**Comment by jmmadsen** [comment]
I'm getting this error as well. I need to use 3.3.4 for the new tab functionality that now works with sorting, but unfortunately this is broken.

**Comment by asaduryan** [comment]
Try to show table component when data is already loaded i think problem is in loading steps , if table renders but data is not loaded yet sort method doesn't work 

try like this

> data={this.props.data?this.props.data: []}

> <BootstrapTable
>           ref={this.table}
>           keyField='_id'
>           noDataIndication="Table is Empty"
>           data={this.props.data?this.props.data: []}
>           columns={columns}
>           filter={filterFactory()}
> ........
>

**Comment by g-akshay** [comment]
Still facing this issue on version `3.3.4`

**Comment by rudza** [comment]
> Still facing this issue on version `3.3.4`

I fixed the issue by updating to v3.3.5
