### ISSUE TITLE
Controlled <input> components lose focus on re-render inside expanded rows

### ISSUE THREAD

**Issue by anttiviljami** [react-bootstrap-table/react-bootstrap-table2#672]
When you add a controlled input field component inside an expanded row, this happens:

![react-bootstrap-table-expand-input-bug](https://user-images.githubusercontent.com/6105650/48782307-974f7400-ece6-11e8-9d08-5dac7e6b2f6c.gif)

Looks like the entire &lt;tbody&gt;  DOM node gets re-created by React on every render of the BootstrapTable component.

Tried to look into it and my best guess is it has something to do with the Context api causing unnecessary re-renders due to https://reactjs.org/docs/context.html#caveats, but couldn't figure it out in reasonable time.

As far as I can see, nothing in the DOM tree should actually cause the React reconciliation algorithm to re-create &lt;tbody&gt;

![react-bootstrap-table-expand-input-bug2](https://user-images.githubusercontent.com/6105650/48782675-602d9280-ece7-11e8-8b79-2efcb097bc41.gif)

**Comment by AllenFang** [comment]
I will look into on it. Anyway, thanks!

**Comment by Mujaddadi** [comment]
Same issue

**Comment by Mujaddadi** [comment]
I have similar issue. But mine is in not in expanded rows but normal cell column. When I add control component with the `selectRow` property. it works. When I add it, it shows similar behavior as above.

**Comment by amsterdamharu** [comment]
Demo of this behavior: https://codesandbox.io/s/github/amsterdamharu/bootstrap-table-extend-bug

**Comment by meghnaraju** [comment]
Hi Allen,

in react bootstrap table, i am unmounting and mounting the table. But once i mount it again i am unable to select any checkbox. if i do display none it works fine. But if i remount it, checkboxes r not working. I have an urgent requirement. pls help

**Comment by mkwenzel** [comment]
I'm wondering if I am running into this same issue - I have a table with checkbox select that is viewable in 2 places, one place is inside an expandable row of another table, the other place it is not. It works fine outside of the expandable table, but inside the click event is registering (I can console.log("click")) but the checkbox does not check.

Gif of issue:
![](https://media.giphy.com/media/ulnb5m5xJdu3yEtxRT/giphy.gif)

**Comment by mkwenzel** [comment]
@anttiviljami @amsterdamharu  Did either of you find a solution for this?

**Comment by anttiviljami** [comment]
No resolution. I just ended up implementing the table myself instead of using react-bootstrap-table. Couldn’t fix this issue within reasonable time.

**Comment by AllenFang** [comment]
Sorry I missed this issue for a long time, my bad,  I will fix this issue in next version, thanks

**Comment by AllenFang** [comment]
Fixed, please check [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/02/09/version-bump.html), **please remember to upgrade the packages which mention in `RELEASE NOTE` to make sure you have correct patch.**

**Comment by AllenFang** [comment]
Again, sorry for lately fixing this issue. Please let me know if this issue still remain. thanks

**Comment by joecrismolina** [comment]
Hi Allen, first of all, thank you for this awesome library, great work! I tried the latest update v2.1.1 and am still having problems with the re-rendering of the expanded row and losing focus on controlled components inside the expanded row. https://codesandbox.io/s/1olom8kk9l
Is this an issue or am I using the expanded row feature in an unintended way? 

best regards, cheers!

**Comment by apausepi** [comment]
Hi Allen, I have the same problem if I don't use editCell. I add the input field directly in formatted column function because I want display all inputs without click.

**Comment by Droid997** [comment]
Hey Guys Any update on this ?
