### ISSUE TITLE
Expanded row column span does not update

### ISSUE THREAD

**Issue by norbertnemeth** [react-bootstrap-table/react-bootstrap-table2#836]
When I display or hide a column with the hidden attribute, then the column span don't update in the expanded row. Basically the expanded row doesn't follow the simple row's col spans.

![image](https://user-images.githubusercontent.com/15226246/53740459-87722f00-3e94-11e9-9578-efc9f2221cd0.png)

**Comment by knightburton** [comment]
That would be awesome if this would be improved!

**Comment by colinwagner** [comment]
I'm having the same issue. It seems visibleColumnSize() is being called and calculated properly but the   prop visibleColumnSize remains the same.

**Comment by AllenFang** [comment]
We will fix this in this weekend, sorry for inconvenience.

**Comment by AllenFang** [comment]
Fixed in newest version, please upgrade all the related packages listed in below notes:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/03/10/version-bump.html

**Comment by meLog** [comment]
![rowExpandBug](https://user-images.githubusercontent.com/12495836/55418796-ae934d80-5573-11e9-890b-87d60b3adf43.png)

after update all packages today the bug is still there. My fault? Or is it back?

thanks for help.

**Comment by rizwan-ishtiaq** [comment]
I am still facing same problem. i am using following
    "react-bootstrap-table-next": "^3.2.1",
    "react-bootstrap-table2-paginator": "^2.1.0",
    "react-bootstrap-table2-toolkit": "^2.1.0",

**Comment by rizwan-ishtiaq** [comment]
I have also tried following combination but bug still persists
react-bootstrap-table-next@3.0.1
react-bootstrap-table2-paginator@2.0.4
react-bootstrap-table2-toolkit@1.3.2
